<!--
@component
The Line component needs to be placed either inside a svelte-konva Layer or Group component. 

### Usage:
```tsx
<Line config={{ points: [0, 0, 60, 30, 300, 90, 30, 100], stroke: "blue", strokeWidth: 10 }} />
```

Further information: [Konva API docs](https://konvajs.org/api/Konva.Line.html), [svelte-konva docs](https://teykey1.github.io/svelte-konva)
-->
<script lang="ts">
	/**
	 * WARNING: This component is autogenerated using the svelteKonvaComponent.hbs template. Do not edit this file manually!
	 */

	import Konva from 'konva';
	import { onMount, onDestroy, beforeUpdate, createEventDispatcher } from 'svelte';
	import type { Writable } from 'svelte/store';
	import { registerEvents } from '$lib/util/events';
	import { getParentContainer, type KonvaParent } from '$lib/util/manageContext';
	import { copyExistingKeys } from '$lib/util/copy';
	import { getOrderManager } from './util/manageOrder';

	export let config: Konva.LineConfig;
	export let handle = new Konva.Line(config);

	let parent: Writable<null | KonvaParent> = getParentContainer();
	let parentOrderManager = getOrderManager();
	let dispatcher = createEventDispatcher();

	$: handle.setAttrs(config);

	onMount(() => {
		$parent!.add(handle);

		handle.on('transformend', () => {
			copyExistingKeys(config, handle.getAttrs());
			config = config;
		});

		handle.on('dragend', () => {
			copyExistingKeys(config, handle.getAttrs());
			config = config;
		});

		registerEvents(dispatcher, handle);
	});

	beforeUpdate(() => {
		parentOrderManager.signalComponentOrder(handle);
	});

	onDestroy(() => {
		handle.destroy();
	});
</script>
