<!--
@component
The Rect component needs to be placed either inside a svelte-konva Layer or Group component.

### Usage:
```tsx
<Rect x={100} y={100} width={100} height={100} fill="blue" />
```

### Static config:
By default svelte-konva will automatically update all changed props on `dragend` and `transformend` events to match the prop values (position, rotation, scale, ...) with the internal Konva state.
If you bind those props they will be updated automatically, otherwise no update of the changed values happens.
In cases this is not needed (eg. the respective values are not bound) or not beneficial you can disable it by passing the `staticConfig = true` prop to the component.
It is recommended to only pass `staticConfig = true` if you indeed run into performance problems connected to dragging and transforming of nodes.

Further information: [Konva API docs](https://konvajs.org/api/Konva.Rect.html), [svelte-konva docs](https://konvajs.org/docs/svelte)
-->
<script lang="ts">
	/**
	 * WARNING: This component is autogenerated using the svelteKonvaComponent.hbs template. Do not edit this file manually!
	 */

	import { Rect as KonvaRect, type RectConfig } from 'konva/lib/shapes/Rect';
	import { onDestroy } from 'svelte';
	import { registerEvents } from '$lib/util/events';
	import { getParentContainer } from '$lib/util/manageContext';
	import { type Props } from '$lib/util/props';

	let {
		staticConfig = false,
		x = $bindable(),
		y = $bindable(),
		scale = $bindable(),
		scaleX = $bindable(),
		scaleY = $bindable(),
		rotation = $bindable(),
		skewX = $bindable(),
		skewY = $bindable(),
		...restProps
	}: Props<RectConfig> = $props();

	export const node = new KonvaRect({
		x,
		y,
		scale,
		scaleX,
		scaleY,
		rotation,
		skewX,
		skewY,
		...restProps
	});

	// Add component to parent container
	getParentContainer().add(node);

	if (!staticConfig) {
		const attrs = node.getAttrs();

		node.on('transformend', () => {
			if (x !== undefined) x = attrs.x;
			if (y !== undefined) y = attrs.y;
			if (scale !== undefined) scale = attrs.scale;
			if (scaleX !== undefined) scaleX = attrs.scaleX;
			if (scaleY !== undefined) scaleY = attrs.scaleY;
			if (rotation !== undefined) rotation = attrs.rotation;
			if (skewX !== undefined) skewX = attrs.skewX;
			if (skewY !== undefined) skewY = attrs.skewY;
		});

		node.on('dragend', () => {
			if (x !== undefined) x = attrs.x;
			if (y !== undefined) y = attrs.y;
		});
	}

	Object.keys(restProps)
		.filter((e) => !e.startsWith('on')) // Do not register svelte-konva event hooks as node attributes (Currently no konva config property starts with "on" so this is the fastest and most inexpensive way to filter out the event hooks from the provided props)
		.forEach((e) => {
			$effect(() => {
				node.setAttr(e, restProps[e]);
			});
		});

	// Register explicit props (not included in restProps)
	$effect(() => {
		node.setAttr('x', x);
	});
	$effect(() => {
		node.setAttr('y', y);
	});
	$effect(() => {
		node.setAttr('scale', scale);
	});
	$effect(() => {
		node.setAttr('scaleX', scaleX);
	});
	$effect(() => {
		node.setAttr('scaleY', scaleY);
	});
	$effect(() => {
		node.setAttr('rotation', rotation);
	});
	$effect(() => {
		node.setAttr('skewX', skewX);
	});
	$effect(() => {
		node.setAttr('skewY', skewY);
	});

	registerEvents(restProps, node);

	onDestroy(() => {
		node.destroy();
	});
</script>
