<!--
@component
The Star component needs to be placed either inside a svelte-konva Layer or Group component. 

### Usage:
```tsx
<Star config={{ x: 100, y: 100, innerRadius: 25, outerRadius: 50, numPoints: 5, fill: "blue" }} />
```

Further information: [Konva API docs](https://konvajs.org/api/Konva.Star.html), [svelte-konva docs](https://konvajs.org/docs/svelte)
-->
<script lang="ts">
	/**
	 * WARNING: This component is autogenerated using the svelteKonvaComponent.hbs template. Do not edit this file manually!
	 */

	import Konva from 'konva';
	import { onMount, onDestroy, createEventDispatcher } from 'svelte';
	import type { Writable } from 'svelte/store';
	import { registerEvents } from '$lib/util/events';
	import { getParentContainer, type KonvaParent } from '$lib/util/manageContext';
	import { copyExistingKeys } from '$lib/util/copy';

	export let config: Konva.StarConfig;
	export let handle = new Konva.Star(config);

	let parent: Writable<null | KonvaParent> = getParentContainer();
	let dispatcher = createEventDispatcher();

	$: handle.setAttrs(config);

	onMount(() => {
		$parent!.add(handle);

		handle.on('transformend', () => {
			copyExistingKeys(config, handle.getAttrs());
			config = config;
		});

		handle.on('dragend', () => {
			copyExistingKeys(config, handle.getAttrs());
			config = config;
		});

		registerEvents(dispatcher, handle);
	});

	onDestroy(() => {
		handle.destroy();
	});
</script>
