<!--
@component
The TextPath component needs to be placed either inside a svelte-konva Layer or Group component. 

### Usage:
```tsx
<TextPath config={{ x: 100, y: 100, fill: "#333", text: "some text", fontSize: 25, data: "M10 10 C0 0 10 150 100 100 S300 150 5.0.300" }} />
```

Further information: [Konva API docs](https://konvajs.org/api/Konva.TextPath.html), [svelte-konva docs](https://teykey1.github.io/svelte-konva)
-->
<script lang="ts">
	/**
	 * WARNING: This component is autogenerated using the svelteKonvaComponent.hbs template. Do not edit this file manually!
	 */

	import Konva from 'konva';
	import { onMount, onDestroy, beforeUpdate, createEventDispatcher } from 'svelte';
	import type { Writable } from 'svelte/store';
	import { registerEvents } from '$lib/util/events';
	import { getParentContainer, type KonvaParent } from '$lib/util/manageContext';
	import { copyExistingKeys } from '$lib/util/copy';
	import { getOrderManager } from './util/manageOrder';

	export let config: Konva.TextPathConfig;
	export let handle = new Konva.TextPath(config);

	let parent: Writable<null | KonvaParent> = getParentContainer();
	let parentOrderManager = getOrderManager();
	let dispatcher = createEventDispatcher();

	$: handle.setAttrs(config);

	onMount(() => {
		$parent!.add(handle);

		handle.on('transformend', () => {
			copyExistingKeys(config, handle.getAttrs());
			config = config;
		});

		handle.on('dragend', () => {
			copyExistingKeys(config, handle.getAttrs());
			config = config;
		});

		registerEvents(dispatcher, handle);
	});

	beforeUpdate(() => {
		parentOrderManager.signalComponentOrder(handle);
	});

	onDestroy(() => {
		handle.destroy();
	});
</script>
