/** List of all svelte-konva components that are autogenerated */
const COMPONENT_LIST = [
	'Circle',
	'Rect',
	'Ellipse',
	'Wedge',
	'Line',
	'Sprite',
	'Image',
	'Text',
	'TextPath',
	'Star',
	'Sprite',
	'Ring',
	'Arc',
	'Label',
	'Path',
	'RegularPolygon',
	'Arrow',
	'Shape'
];

const ACTION_LIST = COMPONENT_LIST.map((componentName) => {
	return {
		type: 'add',
		force: true,
		path: `src/lib/${componentName}.svelte`,
		data: {
			componentName
		},
		templateFile: 'src/templates/svelteKonvaComponent.hbs'
	};
});

export default function (plop) {
	plop.setGenerator('svelteKonvaComponents', {
		description: 'Creates all svelte-konva components that contain similar logic',
		prompts: [],
		actions: ACTION_LIST
	});
}
